shared:
  image: centos:centos7

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"

  skopeo:
    requires: [~commit]
    environment:
      PACKAGE: skopeo
      VERSION: 1.0.0
    steps:
      - install_skopeo: |
          yum install -y wget git make gcc gcc-c++ zip unzip
          wget -q -O go1.15.6.tar.gz https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.15.6.tar.gz
          mkdir /go && cd /go
          export GOROOT=/usr/local/go
          export GOPATH=/go/src
          export PATH=$PATH:$GOROOT/bin
          git clone https://github.com/containers/skopeo $GOPATH/src/github.com/containers/skopeo
          cd $GOPATH/src/github.com/containers/skopeo && make DISABLE_CGO=1 bin/$PACKAGE
      - getDigests: |
          ./bin/skopeo inspect docker://docker.io/alpine:latest
          ./bin/skopeo inspect docker://docker.io/ruby:2.5.5
      - upload: |
          tar -czvf ./bin/$PACKAGE-$VERSION-linux.tar.gz ./bin/$PACKAGE
          curl -T ./bin/$PACKAGE-$VERSION-linux.tar.gz -u$BINTRAY_USER:BINTRAY_APIKEY https://api.bintray.com/content/screwdrivercd/screwdrivercd/skopeo-$VERSION-linux.tar.gz;bt_package=$PACKAGE;bt_version=$VERSION
    secrets:
      - BINTRAY_USER
      - BINTRAY_APIKEY