shared:
  image: centos:centos7

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"

  skopeo:
    requires: [~commit]
    steps:
      - install_skopeo: |
          yum install -y skopeo
